export const referralAbi = [
  {
    inputs: [{ internalType: "string", name: "message", type: "string" }],
    name: "TransactionFailed",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
      { indexed: false, internalType: "bool", name: "status", type: "bool" },
    ],
    name: "Blacklisted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "userId",
        type: "uint256",
      },
      { indexed: false, internalType: "bool", name: "status", type: "bool" },
    ],
    name: "BlacklistedId",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "uint8", name: "version", type: "uint8" },
    ],
    name: "Initialized",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "nft", type: "address" },
      { indexed: true, internalType: "uint256", name: "time", type: "uint256" },
    ],
    name: "NFTSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "token",
        type: "address",
      },
      { indexed: false, internalType: "bool", name: "status", type: "bool" },
      { indexed: true, internalType: "uint256", name: "time", type: "uint256" },
    ],
    name: "PaymentTokenSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "workID",
        type: "uint256",
      },
      { indexed: true, internalType: "address", name: "user", type: "address" },
      {
        indexed: true,
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "time",
        type: "uint256",
      },
    ],
    name: "PayoutByRefIDProcessed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "ref", type: "uint256" },
      { indexed: true, internalType: "address", name: "user", type: "address" },
      {
        indexed: true,
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "time",
        type: "uint256",
      },
    ],
    name: "PayoutByRefProcessed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "genesisKeyTreasury",
        type: "address",
      },
      { indexed: true, internalType: "address", name: "user", type: "address" },
      {
        indexed: true,
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "treasuryAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "time",
        type: "uint256",
      },
    ],
    name: "PayoutByTreasuryProcessed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
      {
        indexed: true,
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "time",
        type: "uint256",
      },
    ],
    name: "PayoutCompleted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
      { indexed: true, internalType: "uint256", name: "time", type: "uint256" },
    ],
    name: "ReferralCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "workedId",
        type: "uint256",
      },
      { indexed: true, internalType: "uint256", name: "time", type: "uint256" },
    ],
    name: "ReferralCreatedWithID",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
      { indexed: true, internalType: "uint256", name: "id", type: "uint256" },
      {
        indexed: false,
        internalType: "uint256",
        name: "time",
        type: "uint256",
      },
    ],
    name: "ReferralMigrated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "role", type: "bytes32" },
      {
        indexed: true,
        internalType: "bytes32",
        name: "previousAdminRole",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "newAdminRole",
        type: "bytes32",
      },
    ],
    name: "RoleAdminChanged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "role", type: "bytes32" },
      {
        indexed: true,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
    ],
    name: "RoleGranted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "role", type: "bytes32" },
      {
        indexed: true,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
    ],
    name: "RoleRevoked",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
      { indexed: true, internalType: "uint256", name: "ref", type: "uint256" },
      {
        indexed: false,
        internalType: "uint256",
        name: "time",
        type: "uint256",
      },
    ],
    name: "UplineCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
      {
        indexed: false,
        internalType: "uint256",
        name: "uplineID",
        type: "uint256",
      },
    ],
    name: "UplineSet",
    type: "event",
  },
  { stateMutability: "payable", type: "fallback" },
  {
    inputs: [],
    name: "DEFAULT_ADMIN_ROLE",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "REF_PROCESSOR",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "SIGNER_ROLE",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "", type: "address" },
      { internalType: "address", name: "", type: "address" },
    ],
    name: "assetSales",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "workId", type: "uint256" },
      { internalType: "address", name: "asset", type: "address" },
    ],
    name: "assetSalesPerID",
    outputs: [{ internalType: "uint256", name: "sales", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "assets",
    outputs: [
      { internalType: "address", name: "asset", type: "address" },
      {
        internalType: "uint256",
        name: "rewardTokenPercentReferrer",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "rewardTokenPercentReferree",
        type: "uint256",
      },
      { internalType: "uint256", name: "cashPercentReferrer", type: "uint256" },
      {
        internalType: "uint256",
        name: "discountPercentReferree",
        type: "uint256",
      },
      { internalType: "uint256", name: "cashPercentTreasury", type: "uint256" },
      { internalType: "bool", name: "isReferrerCashSupported", type: "bool" },
      { internalType: "bool", name: "status", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "workId", type: "uint256" },
      { internalType: "bool", name: "status", type: "bool" },
    ],
    name: "blackListId",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_user", type: "address" },
      { internalType: "bool", name: "_status", type: "bool" },
    ],
    name: "blackListUser",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "workId", type: "uint256" }],
    name: "blackListedID",
    outputs: [{ internalType: "bool", name: "blacklisted", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "blacklists",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_asset", type: "address" },
      { internalType: "uint256", name: "_totalAmount", type: "uint256" },
    ],
    name: "calculateEarning",
    outputs: [
      {
        internalType: "uint256",
        name: "rewardTokenForReferrer",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "rewardTokenForReferree",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "usdEarningForReferrer",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "discountedTotalAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "treasuryCashTotalAmount",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "claimEarning",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "coaAuthAddress",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "userId", type: "uint256" }],
    name: "createReferral",
    outputs: [{ internalType: "bool", name: "result", type: "bool" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "downline", type: "address" }],
    name: "downlineToUplineId",
    outputs: [{ internalType: "uint256", name: "uplineId", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "genesisKeyTreasury",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "genesisKeyTreasuryTotalUSDReceived",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getAllAsset",
    outputs: [{ internalType: "address[]", name: "", type: "address[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getAllPaymentToken",
    outputs: [{ internalType: "address[]", name: "", type: "address[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getAllReferrer",
    outputs: [{ internalType: "address[]", name: "", type: "address[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getAllReferrerIDs",
    outputs: [{ internalType: "uint256[]", name: "", type: "uint256[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "role", type: "bytes32" }],
    name: "getRoleAdmin",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "role", type: "bytes32" },
      { internalType: "address", name: "account", type: "address" },
    ],
    name: "grantRole",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "role", type: "bytes32" },
      { internalType: "address", name: "account", type: "address" },
    ],
    name: "hasRole",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "workId", type: "uint256" }],
    name: "idReferral",
    outputs: [{ internalType: "bool", name: "createdReferal", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "workedId", type: "uint256" }],
    name: "isQualifiedRef",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_prlzAmount", type: "uint256" },
      { internalType: "uint256", name: "_usdtAmount", type: "uint256" },
    ],
    name: "isRefQualifiedForPayout",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "migrateReferrersToIDSystem",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_asset", type: "address" },
      { internalType: "address", name: "_user", type: "address" },
      { internalType: "uint256", name: "refId", type: "uint256" },
      { internalType: "uint256", name: "_qty", type: "uint256" },
      { internalType: "uint256", name: "_total", type: "uint256" },
    ],
    name: "processEarning",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "refereeRecords",
    outputs: [
      { internalType: "uint256", name: "rewardTokenEarned", type: "uint256" },
      { internalType: "uint256", name: "usdEarned", type: "uint256" },
      { internalType: "uint256", name: "totalSalesUSD", type: "uint256" },
      { internalType: "uint256", name: "totalUSDEarned", type: "uint256" },
      {
        internalType: "uint256",
        name: "totalRewardTokenEarned",
        type: "uint256",
      },
      { internalType: "uint256", name: "downlines", type: "uint256" },
      {
        internalType: "uint256",
        name: "numberOfSalesCompleted",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "referrerRecords",
    outputs: [
      { internalType: "uint256", name: "rewardTokenEarned", type: "uint256" },
      { internalType: "uint256", name: "usdEarned", type: "uint256" },
      { internalType: "uint256", name: "totalSalesUSD", type: "uint256" },
      { internalType: "uint256", name: "totalUSDEarned", type: "uint256" },
      {
        internalType: "uint256",
        name: "totalRewardTokenEarned",
        type: "uint256",
      },
      { internalType: "uint256", name: "downlines", type: "uint256" },
      {
        internalType: "uint256",
        name: "numberOfSalesCompleted",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "workId", type: "uint256" }],
    name: "referrerRecordsWithID",
    outputs: [
      { internalType: "uint256", name: "rewardTokenEarned", type: "uint256" },
      { internalType: "uint256", name: "usdEarned", type: "uint256" },
      { internalType: "uint256", name: "totalSalesUSD", type: "uint256" },
      { internalType: "uint256", name: "totalUSDEarned", type: "uint256" },
      {
        internalType: "uint256",
        name: "totalRewardTokenEarned",
        type: "uint256",
      },
      { internalType: "uint256", name: "downlines", type: "uint256" },
      {
        internalType: "uint256",
        name: "numberOfSalesCompleted",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "referrers",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "role", type: "bytes32" },
      { internalType: "address", name: "account", type: "address" },
    ],
    name: "renounceRole",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "role", type: "bytes32" },
      { internalType: "address", name: "account", type: "address" },
    ],
    name: "revokeRole",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "rewardToken",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_asset", type: "address" },
      {
        internalType: "uint256",
        name: "_rewardTokenPercentReferrer",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_rewardTokenPercentReferree",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_cashPercentReferrer",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_discountPercentReferree",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_cashPercentTreasury",
        type: "uint256",
      },
      { internalType: "bool", name: "_isReferrerCashSupported", type: "bool" },
      { internalType: "bool", name: "_status", type: "bool" },
    ],
    name: "setAsset",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_address", type: "address" }],
    name: "setCoaAuthAddress",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_genesisKeyTreasury", type: "address" },
    ],
    name: "setGenesisKeyTreasury",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_token", type: "address" },
      { internalType: "bool", name: "_status", type: "bool" },
    ],
    name: "setPaymentToken",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_rewardToken", type: "address" },
    ],
    name: "setRewardToken",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_user", type: "address" },
      { internalType: "uint256", name: "_uplineID", type: "uint256" },
    ],
    name: "setUplinePublic",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes4", name: "interfaceId", type: "bytes4" }],
    name: "supportsInterface",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "uplines",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  { stateMutability: "payable", type: "receive" },
] as const;
